name: Build and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Frontend Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --verbose
        working-directory: ./frontend

      - name: Lint and Test
        run: |
          npm run lint
          npm run test
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend


  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install --retries 3 -r requirements.txt
        working-directory: ./backend
        shell: bash

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v --tb=short tests/
        working-directory: ./backend
        shell: bash
