name: Build and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Frontend Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --verbose
        working-directory: ./frontend

      - name: Lint code
        run: npm run lint
        working-directory: ./frontend


      - name: Build project
        run: npm run build
        working-directory: ./frontend


  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install --retries 3 -r requirements.txt
        working-directory: ./backend
        shell: bash

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v --tb=short tests/
        working-directory: ./backend
        env:
          DATABASE_URL: mysql+pymysql://root:password@localhost:3306/testdb
        shell: bash
